name: Build and push Docker image

on: 
  push:
    tags:
      - v*.*

jobs:
  release_env:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - id: tag
        run: |
          echo "image_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            

     
  build_and_push:
    needs: [release_env]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ needs.release_env.outputs.image_tag }}

  deploy:
    needs: [release_env, build_and_push]
    runs-on: ubuntu-latest

    steps:
      




      - uses: actions/checkout@v4

      - name: Substitute variables
        env:
          IMAGE_TAG: ${{ needs.release_env.outputs.image_tag }}
        run: |
          ls ${{ github.workspace }}
          envsubst < $GITHUB_WORKSPACE/deployment.yml > $GITHUB_WORKSPACE/deployment-release.yaml
          cat $GITHUB_WORKSPACE/deployment-release.yaml
          ls ${{ github.workspace }}
          
      - name: Install kubectl

        uses: azure/setup-kubectl@v3
        with:
            version: 'v1.31.0'

      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}   
          context: yc-yc-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f $GITHUB_WORKSPACE/deployment-release.yaml
          kubectl rollout status deployment/myapp